### ISSUE TITLE
what is the readout pin of those sketches?

### ISSUE THREAD

**Issue by ggamehdtv** [matthijskooijman/arduino-dsmr#15]
Hello,

Can you tell me what the readout (rX) pin is of those sketches?

best regards,
Justinn

**Comment by matthijskooijman** [comment]
That depends. You configure this library by passing a Serial object (specifically, any `Stream` instance) to it, from which it will read data. In the `read.ino` example, there is:

    P1Reader reader(&Serial1, 2);

Which sets up the library to read from `Serial1`, which is available on e.g. an Arduino Mega. What the RX pin is that corresponds to this serial port depends on the Arduino board you're using, see the docs for the board for more info.

Also note that not all boards (e.g. a Uno) have multiple hardware serial ports, which means you either have to use SoftwareSerial (or similar such as AltSoftSerial) to emulate a second serial port, or use the primary serial port (but then you cannot use the serial port for debugging, if you also open up the serial monitor, you'll create a conflict on the primary serial port).
